let mockData = {
  1: {
    type: "Zdjęcia i filmy z drona",
    voivodeship: "Dolnośląskie",
    city: "Wroclaw",
    street: "Reja",
    description: "dolnoslaskie ogloszenia",
    cost: "2",
    costNegotiation: false,
  },
  2: {
    type: "Zdjęcia i filmy z drona",
    voivodeship: "Łódzkie",
    city: "Łódź",
    street: "Cicha",
    description: "lodzkie lodzkie",
    cost: "43",
    costNegotiation: true,
  },
  3: {
    type: "Zdjęcia i filmy z drona",
    voivodeship: "Mazowieckie",
    city: "Warszawa",
    street: "43",
    description: "mazowieckie ogloszenie",
    cost: "11",
    costNegotiation: false,
  },
  4: {
    type: "Zdjęcia i filmy z drona",
    voivodeship: "Pomorskie",
    city: "Gdańsk",
    street: "1",
    description: "opis gdanski",
    cost: "43",
    costNegotiation: false,
  },
  5: {
    type: "Zdjęcia i filmy z drona",
    voivodeship: "Lubuskie",
    city: "Szczecin",
    street: "Cicha",
    description: "lubuskie ogłoszenia",
    cost: "422",
    costNegotiation: true,
  },
  6: {
    type: "Zdjęcia i filmy z drona",
    voivodeship: "Małopolskie",
    city: "Opole",
    street: "32",
    description: "małopolskie małopolskie opisy",
    cost: "43666",
    costNegotiation: false,
  },
  7: {
    type: "Zdjęcia i filmy z drona",
    voivodeship: "Wielkopomorskie",
    city: "Kraków",
    street: "1",
    description: "opis gdanski",
    cost: "43",
    costNegotiation: false,
  },
  8: {
    type: "Zdjęcia i filmy z drona",
    voivodeship: "Świętokrzyskie",
    city: "Katowice",
    street: "1",
    description: "opis gdanski",
    cost: "43",
    costNegotiation: false,
  },
};

export default mockData;
